# Generated by Django 3.2.8 on 2021-10-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_postais_base',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=30)),
                ('prazo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_postais_db',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sigla_obj', models.CharField(max_length=2)),
                ('classe_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postal_manager.tipos_postais_base')),
            ],
        ),
        migrations.CreateModel(
            name='Objetos_db',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=70)),
                ('data_inclusao', models.DateField()),
                ('classe_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postal_manager.tipos_postais_base')),
            ],
        ),
    ]
