# Generated by Django 3.2.8 on 2021-10-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetos_db',
            name='data_inclusao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
