# Generated by Django 3.2.8 on 2021-10-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_manager', '0003_auto_20211012_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetos_db',
            name='vencimento',
        ),
    ]
